### ISSUE TITLE
Peer-peer code review

### ISSUE THREAD

**Issue by Nkaleth** [anderCM/Leaderboard#4]
## Highlights 
- You did a great job, good comments lines, and better understanding your code. Good module implementations.
- Good git-flow practice.
- No linters errors.
- Well-structured code.

## suggestions

- Kindly implement the project deployment to test it on live demo.
- Your project has no descriptions, kindly add one for better understanding of your project.

https://github.com/anderCM/Leaderboard/blob/abad2a2d1b239826f7a68418c6f746350d8f2d4c/src/index.js#L8

Kindly, change the 'asdsasadasd' comment in order to have a cleaner code.

**Comment by anderCM** [comment]
Issue fixed in this [PR](https://github.com/anderCM/Leaderboard/pull/6)
