### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by dfsalam** [anderCM/Leaderboard#5]
# Highlights :heavy_check_mark: 

- Good use of git-flow. :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Clean code :heavy_check_mark: 
- Linters have passed :heavy_check_mark: 

# Issues
I suggest you use the property <parent>:nth-of-type(even) to change the color alternatively. 
https://github.com/anderCM/Leaderboard/blob/abad2a2d1b239826f7a68418c6f746350d8f2d4c/src/modules/Scores/DisplayScores.js#L14

- I recommend to use inside the HTML when loading external scripts using async attribute, so it doesn't prevent the content load.
- It will be better to use lower camel case to name you functions so that it can be easy to differentiate you classes from functions.

**Comment by anderCM** [comment]
Issue fixed in this [PR](https://github.com/anderCM/Leaderboard/pull/7)
